name: PR build test

on:
  pull_request_target:

jobs:
  build:
    uses: 96boards/oe-rpb-manifest/.github/workflows/build-template.yml@qcom/master
    with:
      local_repo: ${{github.repository}}
      local_ref: refs/pull/${{github.event.pull_request.number}}/head
      branch: ${{github.base_ref}}
    secrets: inherit
